version: "3.0"
services:
  rasa:
    image: rasa/rasa:2.8.15-full
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
  app:
    image: annapapa915/cliobot:1.0.2-deployment
    expose: [5055]
